use std::fs;
use std::path::PathBuf;

use crate::cli;
use plance::prompt;

pub fn delete_project(args: &cli::Cli) {
    // Prompt the user if he/she is sure
    if !prompt("Are you sure? You will lose your effort FOREVER! ") {
        return;
    }

    // Double prompt if you try to delete a directory which hasn't been generated by Plance
    if !PathBuf::from(format!("{}/.plance", args.dir_name.as_str())).exists() {
        if !prompt("WARNING! The given directory is not a plance project. Proceed anyway?") {
            return;
        }
    }

    // Do it!
    match fs::remove_dir_all(PathBuf::from(args.dir_name.clone())) {
        Ok(()) => (),
        Err(e) => {
            eprintln!(
                "ERROR! Couldn't remove directory {}: {}",
                args.dir_name.as_str(),
                e
            );
            return;
        }
    }
}
